---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-cron-checker
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: function-cron-checker

---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
  annotations:
    render.crossplane.io/runtime-docker-cleanup: Stop
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.7.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
  annotations:
    render.crossplane.io/runtime-docker-cleanup: Stop
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.3.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-environment-configs
  annotations:
    render.crossplane.io/runtime-docker-cleanup: Stop
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.1.0